### ISSUE TITLE
Missing license and copyright notice

### ISSUE THREAD

**Issue by tazjin** [divnix/yants#4]
Note that, as all TVL projects, this project is licensed under our top-level [LICENSE](https://cs.tvl.fyi/depot/-/blob/LICENSE) (MIT).

Under the terms of this license you have to both provide the license file and retain our copyright notice for your fork.

I think it's also a bit peculiar that this fork deleted all the git history of yants, as it has a bunch of contributors whose contributions are now not recognised in this fork.

**Comment by astratagem** [comment]
I would like to see this rectified. From the standpoint of an observer, this is not a great look. I assume @blaggacao had no ill intent and that it was an oversight in some way, though I am especially curious about the git history erasure.

More directly on the licensing: in its current state, this fork does not appear to have a license at all.

In addition, I would recommend a direct link to the original source in this fork's README file – for _discoverability_. IIRC, when I first looked through this repo, I had no idea where the original source came from until I saw the message in fcd2f19a2d3ae9d0e7ed2d7be270ed79542c7622.

> Note that, as all TVL projects, this project is licensed under our top-level [LICENSE](https://cs.tvl.fyi/depot/-/blob/LICENSE) (MIT).

@tazjin The [original source file](https://code.tvl.fyi/tree/nix/yants/default.nix) has an SPDX annotation for `Apache-2.0` with a different copyright holder, which differs from the top-level TVL licensing. Considering that, should a fork be dual-licensed under Apache-2.0/MIT?

Edit: also, of course: thank you @tazjin (and other TVL folks) for the original!

**Comment by tazjin** [comment]
> The [original source file](https://code.tvl.fyi/tree/nix/yants/default.nix) has an SPDX annotation for Apache-2.0 with a different copyright holder, which differs from the top-level TVL licensing. Considering that, should a fork be dual-licensed under Apache-2.0/MIT?

Yeah, sorry, need to clean up that header - we were looking into a tool for automating that a while back but it never came to fruition. There's a few outdated, pre-copyright-reassignment headers around unfortunately. Our intention is to have everything under MIT unless there is a separate `LICENSE` file in a subtree (I believe this is explained in the top-level README).

Note that you can clone the source-tree as split out from depot from the remote at `https://code.tvl.fyi/depot.git:/nix/yants.git`.

**Comment by blaggacao** [comment]
Eh, how is it possible I see (conscientiously) this for the first time.

Apologies, please roll back in time and let me follow up asap.

Yes, no ill intentions, neither RE License, nor RE git History, the workflows interacting with a monrepo are simply some blocks apart from a GH fork & PR back, situational unfamiliarity/cost with those workflows is the entire explanation for this not being a git fork.
